In [99]:
#Task1

In [47]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import joblib

In [18]:
df = pd.read_csv('Data .csv')
print(df)

                                                 Path Identity   Expression  \
0   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling   
1   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling   
2   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling   
3   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling   
4   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling   
5   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling   
6   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown      Smiling   
7   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling   
8   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling   
9   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling   
10  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling   
11  /home/zain/Documents/Fcc_Fall2023/Machine Lear..

In [62]:
x = df[['Path', 'Identity', 'Expression']]
y = df[['Age']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [63]:
x_train

Path Identity   Expression
24  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
15  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown      Smiling
17  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
8   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
16  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
12  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
19  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
9   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
32  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
0   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
25  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
5   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
11  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
1   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
37  /home/zain/Documents/Fcc_Fall2023/Machine Lear...   M.Zain  Not smiling
21  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
2   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
29  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown      Smiling
35  /home/zain/Documents/Fcc_Fall2023/Machine Lear...   M.Zain      Smiling
3   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
34  /home/zain/Documents/Fcc_Fall2023/Machine Lear...   M.Zain  Not smiling
23  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
31  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown      Smiling
10  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
22  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
18  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown      Smiling
20  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown      Smiling
7   /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown  Not smiling
14  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown      Smiling
28  /home/zain/Documents/Fcc_Fall2023/Machine Lear...  Unknown      Smiling
38  /home/zain/Documents/Fcc_Fall2023/Machine Lear...   M.Zain      Smiling

In [66]:
y_train

Age
24   44
15   54
17   52
8    47
16   50
12   40
19   57
9    32
32   29
0    35
25   34
5    34
11   41
1    35
37   22
21   41
2    35
29   47
35   22
3    35
34   22
23   44
31   35
10   39
22   49
18   39
20   40
7    42
14   46
28   43
38   22

In [67]:
y_test

Age
33   28
36   22
4    37
13   44
30   55
26   32
6    40
27   51

In [68]:
import os
import skimage
from skimage import io
from skimage import transform

# Specify the path to the folder containing your images
folder_path = '/content/drive/MyDrive/Data_resize_train'

# List all files in the folder
file_names = os.listdir(folder_path)

lst = []
for file_name in file_names:
    try:
        # Construct the full file path by joining the folder path with the file name
        file_path = os.path.join(folder_path, file_name)

        # Read the image using io.imread
        curr_image = io.imread(file_path)

        # Process the image (resize, flatten, normalize) as needed
        img_resize = transform.resize(curr_image, output_shape=(32, 32, 3))
        img_reshape = np.reshape(img_resize, (32 * 32 * 3))
        normalized_img = img_reshape / 255.0

        lst.append(normalized_img)
    except Exception as e:
        print(f"Error processing {file_name}: {e}")
        # Handle the error, for example, skip the problematic file and continue processing the next file
        # continue  # Uncomment this line if you want to skip the problematic file and continue processing the next file

x_train = np.array(lst)
x_train

array([[4.61361015e-05, 0.00000000e+00, 0.00000000e+00, ...,
        1.26105344e-03, 7.07420223e-04, 3.07574010e-04],
       [6.76662822e-04, 5.38254517e-04, 5.84390619e-04, ...,
        5.84390619e-04, 2.61437908e-04, 1.84544406e-04],
       [5.99769319e-04, 7.53556324e-04, 7.38177624e-04, ...,
        2.44521338e-03, 2.30680507e-03, 2.72202999e-03],
       ...,
       [4.30603614e-04, 3.84467512e-04, 3.07574010e-04, ...,
        1.38408304e-03, 8.76585928e-04, 7.68935025e-04],
       [1.73779316e-03, 1.86082276e-03, 1.90695886e-03, ...,
        3.61399462e-03, 2.90657439e-03, 2.50672818e-03],
       [3.27566321e-03, 3.66013072e-03, 3.76778162e-03, ...,
        2.12226067e-03, 1.99923106e-03, 1.24567474e-03]])

In [69]:
y_train= np.array(y_train)
y_train

array([[44],
       [54],
       [52],
       [47],
       [50],
       [40],
       [57],
       [32],
       [29],
       [35],
       [34],
       [34],
       [41],
       [35],
       [22],
       [41],
       [35],
       [47],
       [22],
       [35],
       [22],
       [44],
       [35],
       [39],
       [49],
       [39],
       [40],
       [42],
       [46],
       [43],
       [22]])

In [70]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [87]:
import os
import skimage
from skimage import io
from skimage import transform

# Specify the path to the folder containing your images
folder_path = '/content/drive/MyDrive/Data_resize_test'

# List all files in the folder
file_names = os.listdir(folder_path)

lst = []
for file_name in file_names:
    try:
        # Construct the full file path by joining the folder path with the file name
        file_path = os.path.join(folder_path, file_name)

        # Read the image using io.imread
        curr_image = io.imread(file_path)

        # Process the image (resize, flatten, normalize) as needed
        img_resize = transform.resize(curr_image, output_shape=(32, 32, 3))
        img_reshape = np.reshape(img_resize, (32 * 32 * 3))
        normalized_img = img_reshape / 255.0

        lst.append(normalized_img)
    except Exception as e:
        print(f"Error processing {file_name}: {e}")
        # Handle the error, for example, skip the problematic file and continue processing the next file
        # continue  # Uncomment this line if you want to skip the problematic file and continue processing the next file

x_test = np.array(lst)
x_test

array([[3.75240292e-03, 2.61437908e-03, 2.04536717e-03, ...,
        1.78392926e-03, 1.16878124e-03, 9.84236832e-04],
       [2.29142637e-03, 2.29142637e-03, 2.29142637e-03, ...,
        3.13725490e-03, 2.69127259e-03, 2.22991157e-03],
       [2.36831988e-03, 1.55324875e-03, 3.84467512e-04, ...,
        1.99923106e-04, 5.07497116e-04, 6.15148020e-04],
       ...,
       [3.12187620e-03, 3.13725490e-03, 3.16801230e-03, ...,
        3.07574010e-04, 1.69165705e-04, 1.84544406e-04],
       [3.06036140e-03, 2.78354479e-03, 3.42945021e-03, ...,
        3.12187620e-03, 9.22722030e-05, 9.22722030e-04],
       [3.29104191e-03, 1.66089965e-03, 1.72241446e-03, ...,
        3.42945021e-03, 3.30642061e-03, 2.95271050e-03]])

In [88]:
#We can use joblib to save a model using dump

joblib.dump(model, '/content/Linear_Regressor.pkl')

['/content/Linear_Regressor.pkl']

In [89]:
#We can also load the model from joblib using load
joblib.load('/content/Linear_Regressor.pkl')

LinearRegression()

In [90]:
print("Regression Coefficients: ", model.coef_)
#Printing the regression coffient

Regression Coefficients:  [[ -7.43664292  -3.53552638 -15.87440277 ...  -6.6577299    7.2789425
   11.1307831 ]]


In [91]:
y_test = np.array(y_test)
y_test #converting 2D array of vector to 1D array of vector

array([[28],
       [22],
       [37],
       [44],
       [55],
       [32],
       [40],
       [51]])

In [98]:
print("Regression Coefficients: ", model.coef_)

Regression Coefficients:  [[ -7.43664292  -3.53552638 -15.87440277 ...  -6.6577299    7.2789425
   11.1307831 ]]


In [95]:
y_predict = model.predict(x_test)
MSE = mean_squared_error(y_test, y_predict)
R2 = r2_score(y_test, y_predict)

In [101]:
print("MSE: ", MSE)
print("R2 error: ", R2)
print(model.score(x_train, y_train))

MSE:  151.18160699361255
R2 error:  -0.3621882088682533
1.0
